import React from "react"
import Footer from "../Footer"
import Head from "next/head"
import Header from "../Header"
import { Container } from "@chakra-ui/react"

const Layout = ({ children }) => {
  return (
    <>
      <Head>
        <title>PDX McCord</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Container maxW="90rem">{children}</Container>
      {/* <Footer /> */}
    </>
  )
}

export default Layout
